<div class="row">
    <div class="large-12 columns">
        <h1>Welcome</h1>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <form name="login" action="" method="post">
                <div class="row">
                    <div class="small-3 columns">&nbsp;</div>
                    <div class="small-6 columns">
                         <?php echo $viewmodel->getDecoratedMessage();?>

                        <div class="row">

                            <div class="small-3 columns">
                                <label for="username" class="right inline">Username</label>
                            </div>
                            <div class="small-9 columns">
                                <input type="text" id="username" name="username" placeholder="Username">
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-3 columns">
                                <label for="password" class="right inline">Password</label>
                            </div>
                            <div class="small-9 columns">
                                <input type="password" id="password" name="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-3 columns">&nbsp;</div>
                            <div class="small-9 columns">
                                <button class="button small" name="submit">Submit</button>
                            </div>
                        </div>
                    </div>
                    <div class="small-3 columns">&nbsp;</div>
                </div>
            </form>
        </div>
    </div>
</div>